os_username: "{{ lookup('env','OS_USERNAME') }}"
os_password: "{{ lookup('env','OS_PASSWORD') }}"
os_tenant_name: "{{ lookup('env','OS_TENANT_NAME') }}"
os_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
os_region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"

cloud_name: rdocloud
latest_guest_image:
    newton: CentOS-7-x86_64-GenericCloud-1708
    ocata: CentOS-7-x86_64-GenericCloud-1708
    pike: CentOS-7-x86_64-GenericCloud-1708
    master: CentOS-7-x86_64-GenericCloud-1708

bmc_flavor: m1.small
baremetal_flavor: m1.large
undercloud_flavor: m1.large2
provision_net_cidr: 192.168.24.0/24

nameserver_from_virthost: false
custom_nameserver:
    - 38.145.33.91
    - 38.145.32.66
    - 38.145.32.79
undercloud_undercloud_nameservers: "{{ custom_nameserver }}"
external_net: '38.145.32.0/22'
overcloud_dns_servers: "{{ custom_nameserver }}"
ntp_server: 'pool.ntp.org'
boot_from_volume: true

docker_registry_host: docker.io
docker_registry_namespace: "tripleo{{ release }}"

mtu: 1350
mtu_interface:
    - eth0
    - eth1
    - "{% if network_isolation|default(true)|bool %}eth2{% endif %}"

undercloud_local_mtu: "{{ mtu }}"
overcloud_neutron_global_physnet_mtu: "{{ mtu }}"

run_tripleo_validations: True
