---
- name: Create undercloud custom tht script
  template:
    src: "{{ undercloud_custom_tht_script }}"
    dest: "{{ working_dir }}/undercloud-custom-tht-script.sh"
    mode: 0755

- name: Checkout custom tht heat templates from src
  shell: >
    set -o pipefail &&
    {{ working_dir }}/undercloud-custom-tht-script.sh 2>&1 {{ timestamper_cmd }} >
    {{ undercloud_custom_tht_log }}
